name: ButtonControl
version: 1.3
main: viper.ButtonControl
api-version: 1.21
author: viper
description: Ein Plugin, um Türen, Redstone-Lampen und Notenblöcke mit einem Button oder Tageslichtsensor zu steuern.

commands:
  bc:
    description: Steuert das ButtonControl Plugin
    usage: /<command> [info|reload|note <instrument>]
    aliases: [buttoncontrol]

permissions:
  buttoncontrol.reload:
    description: Erlaubt das Neuladen der Plugin-Konfiguration
    default: op
  buttoncontrol.note:
    description: Erlaubt das Ändern des Notenblock-Instruments
    default: true